[dependencies]
pyo3 = { workspace = true }
s3z = { path = "../../crates/core" }
tokio = { workspace = true }

[lib]
crate-type = ["cdylib"]
name = "s3z_py"

[lints]
workspace = true

[package]
description = "Python bindings for s3z — S3 ops, but fearlessly fast!"
name = "s3z-python"
readme = "../../README.md"
version = "0.1.0-rc.1"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
