"""Generate Python API reference MDX from the installed s3z module.

Usage:
    python scripts/generate-python-api.py > content/docs/python/api.mdx

Requires the s3z wheel to be installed (maturin develop --release).
Reads class/method/function docstrings and signatures via inspect.

Output structure matches the Node.js API reference page:
  S3Client → Configuration → Options → Results → Utilities
"""

from __future__ import annotations

import inspect
import sys


def mdx_escape(s: str) -> str:
    return s.replace("|", "\\|")


def format_signature(obj: object) -> str | None:
    try:
        return str(inspect.signature(obj))
    except (ValueError, TypeError):
        return None


def clean_self(sig: str) -> str:
    return sig.replace("(self, /, ", "(").replace("(self, /)", "()")


def props_table(cls: type) -> list[str]:
    """Render a property/field table for a class."""
    lines: list[str] = []
    props = []
    for name, obj in sorted(inspect.getmembers(cls)):
        if name.startswith("_"):
            continue
        doc = getattr(obj, "__doc__", "") or ""
        if isinstance(inspect.getattr_static(cls, name, None), property):
            props.append((name, doc.strip()))
        elif not callable(obj):
            props.append((name, doc.strip()))
    if props:
        lines.append("| Property | Description |")
        lines.append("|---|---|")
        for name, doc in props:
            lines.append(f"| `{name}` | {mdx_escape(doc)} |")
        lines.append("")
    return lines


def method_table(cls: type) -> list[str]:
    """Render a method summary table for a class."""
    lines: list[str] = []
    methods = []
    for name, obj in sorted(inspect.getmembers(cls)):
        if name.startswith("_"):
            continue
        if not callable(obj):
            continue
        if isinstance(inspect.getattr_static(cls, name, None), property):
            continue
        sig = format_signature(obj)
        doc = getattr(obj, "__doc__", "") or ""
        if sig:
            display = clean_self(sig)
            methods.append((name, display, doc.strip()))
    if methods:
        lines.append("| Method | Signature | Description |")
        lines.append("|---|---|---|")
        for name, sig, doc in methods:
            lines.append(
                f"| `{name}` | `client.{name}{sig}` | {mdx_escape(doc)} |"
            )
        lines.append("")
    return lines


def main() -> None:
    try:
        import s3z.s3z as mod
    except ImportError:
        print(
            "Error: s3z not installed. Run: maturin develop --release",
            file=sys.stderr,
        )
        sys.exit(1)

    # Collect everything
    classes = {}
    functions = {}
    for name, obj in inspect.getmembers(mod):
        if name.startswith("_"):
            continue
        if inspect.isclass(obj):
            classes[name] = obj
        elif inspect.isfunction(obj) or inspect.isbuiltin(obj):
            functions[name] = obj

    lines: list[str] = [
        "---",
        "title: API Reference",
        "description: Complete API reference for the s3z Python package.",
        "---",
        "",
        "{/* Auto-generated by scripts/generate-python-api.py */}",
        "{/* Do not edit — regenerate with: python scripts/generate-python-api.py */}",
        "",
    ]

    # --- S3Client ---
    if "S3Client" in classes:
        cls = classes["S3Client"]
        doc = (cls.__doc__ or "").strip()
        sig = format_signature(cls)
        lines.append("## S3Client")
        lines.append("")
        if doc:
            lines.append(doc)
            lines.append("")
        if sig:
            lines.append("```python")
            lines.append(f"client = S3Client({clean_self(sig).strip('()')})")
            lines.append("```")
            lines.append("")
        lines.extend(method_table(cls))

    # --- Configuration ---
    config_types = ["Config", "CredentialSource", "StaticCredentials"]
    has_config = any(c in classes for c in config_types)
    if has_config:
        lines.append("## Configuration")
        lines.append("")
        for name in config_types:
            if name not in classes:
                continue
            cls = classes[name]
            doc = (cls.__doc__ or "").strip()
            sig = format_signature(cls)
            lines.append(f"### {name}")
            lines.append("")
            if doc:
                lines.append(doc)
                lines.append("")
            if sig:
                display = clean_self(sig)
                # Skip empty constructors for enums/wrappers
                if display != "()":
                    lines.append("```python")
                    lines.append(f"{name}{display}")
                    lines.append("```")
                    lines.append("")
            lines.extend(props_table(cls))

    # --- Functions (utilities) ---
    if functions:
        # Place under Configuration since they create credentials
        for name, fn in sorted(functions.items()):
            sig = format_signature(fn)
            doc = getattr(fn, "__doc__", "") or ""
            lines.append(f"### {name}")
            lines.append("")
            if sig:
                lines.append("```python")
                lines.append(f"{name}{sig}")
                lines.append("```")
                lines.append("")
            if doc:
                lines.append(doc.strip())
                lines.append("")

    # --- Results ---
    result_types = [
        "FileUploadResult",
        "FileDownloadResult",
        "ObjectInfo",
    ]
    has_results = any(r in classes for r in result_types)
    if has_results:
        lines.append("## Results")
        lines.append("")
        for name in result_types:
            if name not in classes:
                continue
            cls = classes[name]
            doc = (cls.__doc__ or "").strip()
            lines.append(f"### {name}")
            lines.append("")
            if doc:
                lines.append(doc)
                lines.append("")
            lines.extend(props_table(cls))

    print("\n".join(lines))


if __name__ == "__main__":
    main()
