[build-dependencies]
napi-build = { workspace = true }

[dependencies]
napi = { workspace = true }
napi-derive = { workspace = true }
s3z = { path = "../../crates/core" }
tokio = { workspace = true }

[lib]
crate-type = ["cdylib"]
name = "s3z_js"

[lints]
workspace = true

[package]
description = "Node.js bindings for s3z — S3 ops, but fearlessly fast!"
name = "s3z-node"
readme = "../../README.md"
version = "0.0.0"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
