/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The s3z S3 client. */
export declare class S3Client {
  /**
  * Create a new S3 client.
  *
  * # Errors
  *
  * Returns an error if credential resolution or HTTP client setup fails.
  */
  static create(config: S3Config): Promise<S3Client>
  /**
  * Upload files/directories to S3.
  *
  * # Errors
  *
  * Returns an error if any file upload or source expansion fails.
  */
  upload(options: UploadOptions): Promise<Array<FileUploadResult>>
  /**
  * Download objects under a prefix to a local directory.
  *
  * # Errors
  *
  * Returns an error if listing, any download, or file I/O fails.
  */
  download(options: DownloadOptions): Promise<Array<FileDownloadResult>>
  /**
  * List all objects under a prefix.
  *
  * # Errors
  *
  * Returns an error if any listing page fetch fails.
  */
  list(options: ListOptions): Promise<Array<ObjectInfo>>
}

/** Download options. */
export interface DownloadOptions {
  /** Source S3 bucket. */
  bucket: string
  /** Key prefix. */
  prefix: string
  /** Local destination directory. */
  destDir: string
  /** Number of files downloaded in parallel (default 32). */
  workers?: number
  /** Parts per file concurrency (default 8). */
  concurrencyPerFile?: number
}

/** Result of a single file download. */
export interface FileDownloadResult {
  /** Local path the file was written to. */
  dest: string
  /** S3 key that was downloaded. */
  key: string
  /** Number of parts used. */
  parts: number
  /** File size in bytes. */
  size: number
}

/** Result of a single file upload. */
export interface FileUploadResult {
  /** `ETag` returned by S3. */
  etag: string
  /** S3 key the file was written to. */
  key: string
  /** Number of parts used (1 = single PUT). */
  parts: number
  /** File size in bytes. */
  size: number
  /** Local path that was uploaded. */
  source: string
}

/** List options. */
export interface ListOptions {
  /** S3 bucket. */
  bucket: string
  /** Key prefix. */
  prefix: string
  /** Optional delimiter for directory grouping. */
  delimiter?: string
}

/** Metadata for a single S3 object. */
export interface ObjectInfo {
  /** Object key. */
  key: string
  /** Object size in bytes. */
  size: number
  /** `ETag`. */
  etag: string
  /** Last modified timestamp (ISO 8601). */
  lastModified: string
}

/** Configuration for the S3 client. */
export interface S3Config {
  /** AWS region (e.g. "us-east-1"). */
  region: string
  /** AWS access key ID. If omitted, reads from `AWS_ACCESS_KEY_ID` env var. */
  accessKey?: string
  /** AWS secret access key. If omitted, reads from `AWS_SECRET_ACCESS_KEY` env var. */
  secretKey?: string
  /** Custom endpoint URL for S3-compatible backends (`MinIO`, R2, GCS). */
  endpoint?: string
}

/** Upload options. */
export interface UploadOptions {
  /** Local file/directory paths to upload. */
  sources: Array<string>
  /** Target S3 bucket. */
  bucket: string
  /** Key prefix in the bucket. */
  prefix: string
  /** Number of files uploaded in parallel (default 32). */
  workers?: number
  /** Parts per file concurrency (default 8). */
  concurrencyPerFile?: number
}
